# Generated by Django 4.0.3 on 2022-05-19 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Branch', models.CharField(choices=[('MSc_Integrated', 'MSc_Integrated'), ('BE_Civil', 'BE_Civil'), ('BE_Mechanical', 'BE_Mechanical'), ('BE_Biotech', 'Biotech'), ('BE_EEE', 'BE_EEE'), ('BE_ECE', 'BE_ECE'), ('BE_CS', 'BE_CS'), ('BE_IT', 'BE_IT'), ('BE_Industrial', 'BE_Industrial'), ('BE_Manufacturing', 'BE_Manufacturing'), ('BE_Material_Science', 'BE_Material_Science')], max_length=100)),
                ('RollNumber', models.CharField(max_length=10)),
                ('Campus', models.CharField(choices=[('CEG', 'CEG'), ('ACT', 'ACT'), ('SAP', 'SAP')], max_length=3)),
                ('BloodGroup', models.CharField(choices=[('B+', 'B+'), ('A+', 'A+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A1B+', 'A1B+'), ('B-', 'B-'), ('A-', 'A-'), ('O-', 'O-'), ('AB-', 'AB-'), ('A1B-', 'A1B-')], max_length=7)),
                ('PhoneNumber', models.CharField(max_length=13)),
                ('Address', models.CharField(choices=[('Arumbakkam', 'Arumbakkam'), ('AnnaNagar', 'AnnaNagar'), ('Adyar', 'Adyar'), ('Alwarpet', 'Alwarpet'), ('Alappakkam', 'Alappakkam'), ('AlwarThiruNagar', 'AlwarThiruNagar'), ('Ayyanambakkam', 'Ayyanambakkam'), ('BesantNagar', 'BesantNagar'), ('CMBT', 'CMBT'), ('Chrompet', 'Chrompet'), ('Egmore', 'Egmore'), ('Guindy', 'Guindy'), ('Iyyapanthangal', 'Iyyapanthangal'), ('KKNagar', 'KKNagar'), ('Kattupakkam', 'Kattupakkam'), ('Kodambakkam', 'Kodambakkam'), ('Kundrathur', 'Kundrathur'), ('Meenambakkam', 'Meenambakkam'), ('Maduravayal', 'Maduravayal'), ('Mylapore', 'Mylapore'), ('Mogappair', 'Mogappair'), ('Nandanam', 'Nandanam'), ('Nungambakkam', 'Nungambakkam'), ('Nandambakkam', 'Nandambakkam'), ('Nasaratpet', 'Nasaratpet'), ('Porur', 'Porur'), ('Poonamallee', 'Poonamallee'), ('Purasaiwalkam', 'Purasaiwalkam'), ('Pudupet', 'Pudupet'), ('Royapuram', 'Royapuram'), ('Ramapuram', 'Ramapuram'), ('Saidapet', 'Saidapet'), ('TNagar', 'TNagar'), ('Teynampet', 'Teynampet'), ('Thiruvanmiyur', 'Thiruvanmiyur'), ('Virugambakkam', 'Virugambakkam'), ('Vadapalani', 'Vadapalani'), ('Velachery', 'Velachery'), ('Valasaravakkam', 'Valasaravakkam')], max_length=255)),
                ('ReferenceID', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('ValidUntil', models.DateField()),
                ('User1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(choices=[('Arumbakkam', 'Arumbakkam'), ('AnnaNagar', 'AnnaNagar'), ('Adyar', 'Adyar'), ('Alwarpet', 'Alwarpet'), ('Alappakkam', 'Alappakkam'), ('AlwarThiruNagar', 'AlwarThiruNagar'), ('Ayyanambakkam', 'Ayyanambakkam'), ('BesantNagar', 'BesantNagar'), ('CMBT', 'CMBT'), ('Chrompet', 'Chrompet'), ('Egmore', 'Egmore'), ('Guindy', 'Guindy'), ('Iyyapanthangal', 'Iyyapanthangal'), ('KKNagar', 'KKNagar'), ('Kattupakkam', 'Kattupakkam'), ('Kodambakkam', 'Kodambakkam'), ('Kundrathur', 'Kundrathur'), ('Meenambakkam', 'Meenambakkam'), ('Maduravayal', 'Maduravayal'), ('Mylapore', 'Mylapore'), ('Mogappair', 'Mogappair'), ('Nandanam', 'Nandanam'), ('Nungambakkam', 'Nungambakkam'), ('Nandambakkam', 'Nandambakkam'), ('Nasaratpet', 'Nasaratpet'), ('Porur', 'Porur'), ('Poonamallee', 'Poonamallee'), ('Purasaiwalkam', 'Purasaiwalkam'), ('Pudupet', 'Pudupet'), ('Royapuram', 'Royapuram'), ('Ramapuram', 'Ramapuram'), ('Saidapet', 'Saidapet'), ('TNagar', 'TNagar'), ('Teynampet', 'Teynampet'), ('Thiruvanmiyur', 'Thiruvanmiyur'), ('Virugambakkam', 'Virugambakkam'), ('Vadapalani', 'Vadapalani'), ('Velachery', 'Velachery'), ('Valasaravakkam', 'Valasaravakkam')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(choices=[('Arumbakkam', 'Arumbakkam'), ('AnnaNagar', 'AnnaNagar'), ('Adyar', 'Adyar'), ('Alwarpet', 'Alwarpet'), ('Alappakkam', 'Alappakkam'), ('AlwarThiruNagar', 'AlwarThiruNagar'), ('Ayyanambakkam', 'Ayyanambakkam'), ('BesantNagar', 'BesantNagar'), ('CMBT', 'CMBT'), ('Chrompet', 'Chrompet'), ('Egmore', 'Egmore'), ('Guindy', 'Guindy'), ('Iyyapanthangal', 'Iyyapanthangal'), ('KKNagar', 'KKNagar'), ('Kattupakkam', 'Kattupakkam'), ('Kodambakkam', 'Kodambakkam'), ('Kundrathur', 'Kundrathur'), ('Meenambakkam', 'Meenambakkam'), ('Maduravayal', 'Maduravayal'), ('Mylapore', 'Mylapore'), ('Mogappair', 'Mogappair'), ('Nandanam', 'Nandanam'), ('Nungambakkam', 'Nungambakkam'), ('Nandambakkam', 'Nandambakkam'), ('Nasaratpet', 'Nasaratpet'), ('Porur', 'Porur'), ('Poonamallee', 'Poonamallee'), ('Purasaiwalkam', 'Purasaiwalkam'), ('Pudupet', 'Pudupet'), ('Royapuram', 'Royapuram'), ('Ramapuram', 'Ramapuram'), ('Saidapet', 'Saidapet'), ('TNagar', 'TNagar'), ('Teynampet', 'Teynampet'), ('Thiruvanmiyur', 'Thiruvanmiyur'), ('Virugambakkam', 'Virugambakkam'), ('Vadapalani', 'Vadapalani'), ('Velachery', 'Velachery'), ('Valasaravakkam', 'Valasaravakkam')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleNumber', models.CharField(max_length=10)),
                ('VehicleType', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike')], max_length=5)),
                ('SeatsAvailable', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('Status', models.BooleanField()),
                ('HomeArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.volunteerarea')),
                ('RollNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.details')),
                ('User1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HomeArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentarea')),
                ('RollNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.details')),
                ('User1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('StudentArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentarea')),
                ('StudentUser1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentUser1', to=settings.AUTH_USER_MODEL)),
                ('Volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.volunteer')),
                ('VolunteerUser1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VolunteerUser1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.TimeField(auto_now_add=True)),
                ('PickupArea', models.CharField(choices=[('Arumbakkam', 'Arumbakkam'), ('AnnaNagar', 'AnnaNagar'), ('Adyar', 'Adyar'), ('Alwarpet', 'Alwarpet'), ('Alappakkam', 'Alappakkam'), ('AlwarThiruNagar', 'AlwarThiruNagar'), ('Ayyanambakkam', 'Ayyanambakkam'), ('BesantNagar', 'BesantNagar'), ('CMBT', 'CMBT'), ('Chrompet', 'Chrompet'), ('Egmore', 'Egmore'), ('Guindy', 'Guindy'), ('Iyyapanthangal', 'Iyyapanthangal'), ('KKNagar', 'KKNagar'), ('Kattupakkam', 'Kattupakkam'), ('Kodambakkam', 'Kodambakkam'), ('Kundrathur', 'Kundrathur'), ('Meenambakkam', 'Meenambakkam'), ('Maduravayal', 'Maduravayal'), ('Mylapore', 'Mylapore'), ('Mogappair', 'Mogappair'), ('Nandanam', 'Nandanam'), ('Nungambakkam', 'Nungambakkam'), ('Nandambakkam', 'Nandambakkam'), ('Nasaratpet', 'Nasaratpet'), ('Porur', 'Porur'), ('Poonamallee', 'Poonamallee'), ('Purasaiwalkam', 'Purasaiwalkam'), ('Pudupet', 'Pudupet'), ('Royapuram', 'Royapuram'), ('Ramapuram', 'Ramapuram'), ('Saidapet', 'Saidapet'), ('TNagar', 'TNagar'), ('Teynampet', 'Teynampet'), ('Thiruvanmiyur', 'Thiruvanmiyur'), ('Virugambakkam', 'Virugambakkam'), ('Vadapalani', 'Vadapalani'), ('Velachery', 'Velachery'), ('Valasaravakkam', 'Valasaravakkam')], max_length=50)),
                ('Note', models.CharField(max_length=100)),
                ('User1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.volunteer')),
            ],
        ),
    ]
